name: List Folders Workflow

# Pull request trigger
on:
  pull_request:
    branches:
      - main

# Manual Trigger
# No branch defined hence can run from any branch
on: 
  workflow_dispatch:
  
# Actions:
jobs:
  # Job id to identify must be unique
  list-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: List folders
        run: ls -d */
