name: List Folders Workflow

# Pull request trigger
on:
  pull_request:
    branches:
      - main

  # Manual Trigger
  # No branch defined hence can run from any branch
  workflow_dispatch:
  
# Actions:
jobs:
  # Job id to identify must be unique
  list-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
       
      - name: Print statement
        run: echo "Hello, workflow is running!"

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'

      # Downloads all the NuGet packages and dependencies like MSUnit, EFCore
      # Fail here means missing packages
      - name: Restore dependencies
        run: dotnet restore StudentGradeProcessor.slnx

      # Compiles the C# code into EXE or DLL files, no restore as we already did that
      # Configuration can be Debug for development but Release for production and CI
      # Fail here means compile time error
      - name: Build project
        run: dotnet build --no-restore --confirguration Release

      # Runs unit test documents
      # Fail here means logic error
      - name: Test project
        run: dotnet test --no-build --verbose minimal
